import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./(root)/components";
import "./globals.css";


const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${spaceGrotesk.variable} antialiased`}
        >
          <SidebarProvider>
            <div className="flex h-screen" role="application" aria-label="Aplicación Frontium Videos">
              <aside className="flex-shrink-0" aria-label="Navegación principal">
                <AppSidebar />
                <SidebarTrigger />
              </aside>
              <main className="flex-1 overflow-auto" role="main" aria-label="Contenido principal">
                {children}
              </main>
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
